version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "root"
      POSTGRES_DB: "word"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 3s
      timeout: 60s
      retries: 5
    volumes:
      # ðŸ‘‡ Postgres 18+ expects a single mount at /var/lib/postgresql
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql
    networks:
      - app-network
    restart: unless-stopped

  inngest:
    image: inngest/inngest:latest
    ports:
      - "8288:8288"
    command: >
      inngest dev -u http://host.docker.internal:8086/inngest/serve
    environment:
      INNGEST_DEV: 1


networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
